terraform {
  source = "../../../../modules/uc-aws-infra"
}

# Include all settings from the root terragrunt.hcl file
include "root" {
  path = find_in_parent_folders("root.hcl")
}

# Include environment-specific settings
include "env" {
  path = find_in_parent_folders("env.hcl")
}

# Include region-specific settings
include "region" {
  path   = find_in_parent_folders("region.hcl")
  expose = true
}

# Provider configuration is generated by root.hcl
# Region will be passed via inputs to the module

# Define dependencies
dependency "account_admin" {
  config_path = "../account-admin"
}

# Pass region from region.hcl and admin_group_id from account_admin module to terraform module
inputs = {
  region         = include.region.locals.aws_region
  admin_group_id = dependency.account_admin.outputs.admin_group.id
}

# Other variables are defined in terraform.tfvars file
# Terragrunt will automatically load terraform.tfvars